### ISSUE TITLE
Add support for active power rate configuration

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [ViRuSTriNiTy/OpenInverterGateway#1]
The firmware should support configuration of the active power rate to limit export to the grid. 

Side note:

There is already an open PR in the original repo to address this but it seems dead:

https://github.com/OpenInverterGateway/OpenInverterGateway/pull/271

**Comment by ViRuSTriNiTy** [comment]
Implemented via https://github.com/OpenInverterGateway/OpenInverterGateway/pull/365

**Comment by mgraupner** [comment]
@ViRuSTriNiTy: Great addition, does it store the setting permanently? Right now I have to set the value every day again via the web interface (register 3, percentage, write, holding register), which is pretty annoying.

Edit: Seems like you're doing the exact same thing, just programmatically, right? Does your inverter store this value?

**Comment by ViRuSTriNiTy** [comment]
@mgraupner Yes, you have to set it when the inverter comes back online. I currently do this via Scheduler in Home Assistant  each morning. The register documentation describes a register to define certain values like the power rate as permanent. Sadly this does not work on my inverter or I did something wrong while testing this. Have you tried making the values permanent?

**Comment by mgraupner** [comment]
Same for me, I have to reapply these values every day. I am using a cronjob and the web-to-modbus interface at the moment but will be switching to your mqtt solution as soon as I can update the firmware.
I've read that you can save these parameters permanently with the original firmware, but don't know if it's just reapplying them or actually saving them in the inverter.
